# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_MACH_EXYNOS7885_A30_GLOBAL) := \
    exynos/dtb/exynos7885.dtb

dtbo-$(CONFIG_MACH_EXYNOS7885_A30_GLOBAL) := \
    exynos/dtbo/exynos7904-a30_swa_open_00.dtbo \
    exynos/dtbo/exynos7904-a30_swa_open_01.dtbo \
    exynos/dtbo/exynos7904-a30_swa_open_02.dtbo

dtb-$(CONFIG_MACH_EXYNOS7885_A30S_GLOBAL) := \
    exynos/dtb/exynos7885.dtb

dtbo-$(CONFIG_MACH_EXYNOS7885_A30S_GLOBAL) := \
    exynos/dtbo/exynos7904-a30s_eur_open_00.dtbo \
    exynos/dtbo/exynos7904-a30s_eur_open_01.dtbo \
    exynos/dtbo/exynos7904-a30s_eur_open_02.dtbo \
    exynos/dtbo/exynos7904-a30s_eur_open_03.dtbo

dtb-$(CONFIG_MACH_EXYNOS7885_A40_GLOBAL) := \
    exynos/dtb/exynos7885.dtb

dtbo-$(CONFIG_MACH_EXYNOS7885_A40_GLOBAL) := \
    exynos/dtbo/exynos7904-a40_eur_open_00.dtbo \
    exynos/dtbo/exynos7904-a40_eur_open_01.dtbo

dtb-$(CONFIG_MACH_EXYNOS7885_M20_GLOBAL) := \
    exynos/dtb/exynos7904-m20lte_swa_open_04.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_M30_GLOBAL) := \
    exynos/dtb/exynos7904-m30lte_swa_open_00.dtb \
    exynos/dtb/exynos7904-m30lte_swa_open_01.dtb \
    exynos/dtb/exynos7904-m30lte_swa_open_03.dtb \
    exynos/dtb/exynos7904-m30lte_swa_open_04.dtb

always         := $(dtb-y) $(dtbo-y)
clean-files    := *.dtb *.dtbo
