# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_MACH_EXYNOS7885_A30_GLOBAL) := \
    exynos/dtbo/exynos7904-a30_swa_open_00.dtbo \
    exynos/dtbo/exynos7904-a30_swa_open_01.dtbo \
    exynos/dtbo/exynos7904-a30_swa_open_02.dtbo

dtb-$(CONFIG_MACH_EXYNOS7885_A30S_GLOBAL) := \
    exynos/dtbo/exynos7885.dtb \
    exynos/dtbo/exynos7904-a30s_eur_open_00.dtbo \
    exynos/dtbo/exynos7904-a30s_eur_open_01.dtbo \
    exynos/dtbo/exynos7904-a30s_eur_open_02.dtbo \
    exynos/dtbo/exynos7904-a30s_eur_open_03.dtbo

dtb-$(CONFIG_MACH_EXYNOS7885_A40_GLOBAL) := \
	exynos/dtbo/exynos7904-a40_eur_open_00.dtbo \
	exynos/dtbo/exynos7904-a40_eur_open_01.dtbo

always         := $(dtb-y) $(dtbo-y)
clean-files    := *.dtb *.dtbo
